// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Data.Migrations
{
    [DbContext(typeof(MiniCourseDbContext))]
    [Migration("20220507120459_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("Shared.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "The 1 post has some interesting content check it out",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "The 2 post has some interesting content check it out",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "The 3 post has some interesting content check it out",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "The 4 post has some interesting content check it out",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "The 5 post has some interesting content check it out",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "The 6 post has some interesting content check it out",
                            Title = "Post 6"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
